package br.net.ipp.enums;

public enum TipoDeParceria {
	EMPRESAS_PARCEIRAS,
	PARCEIROS_INSTITUCIONAIS,
	PATROCINADORES,
	EMPRESAS_COLABORADORAS,
	FORNECEDORES_AMIGOS,
	CLUBES_ASSOSSIADOS,
	APOIADORES,
	EMPRESAS_AMIGAS,
	CONTATOS;
}
