package br.net.ipp.enums;

public enum MotivoDaDispensa {
	TERMINO_DE_CONTRATO,
	PEDIDO_DE_DEMISSAO,
	O_APRENDIZ_ATINGIU_A_IDADE_LIMITE_DE_24_ANOS,
	FALTA_DICIPLINAR_GRAVE_ART_482_DA_CLT,
	AUSENCIA_INJUSTIFICADA_DA_ESCOLA_QUE_IMPLIQUE_EM_PERDA_DO_ANO_LETIVO,
	DESEMPENHO_INSUFICIENTE_OU_INADAPTACAO_DO_APRENDIZ_ACOMPANHA_LAUDO,
	ENCERRAMENTO_DAS_ATIVIDADES_DA_EMPRESA,
	MORTE_DO_EMPREGADOR_CONSTITUIDO_COMO_EMPRESA_INDIVIDUAL,
	FALENCIA,
	OUTROS;
}